# Generated by Django 2.0.6 on 2018-08-19 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0006_foodtypes_goods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='childcname',
            new_name='childcidname',
        ),
    ]
